version: '2'
services:
  cyanite:
    build: ./apps/cyanite
    ports:
      - 8080:8080
      - 2003:2003
    depends_on:
      - cassandra
      - cassandra_schema
    networks:
      - cyanite
  cassandra:
    image: cassandra:3.0
    networks:
      - cyanite
  cassandra_schema:
    image: cassandra:3.0
    networks:
      - cyanite
    command: cqlsh cassandra -f /tmp/schema.cql
    volumes:
      - ./apps/cassandra/schema.cql:/tmp/schema.cql
    depends_on:
      - cassandra
  collectd:
    build: ./apps/collectd
    depends_on:
      - cyanite
    networks:
      - cyanite
  graphite-api:
    build: ./apps/graphite-api
    depends_on:
      - cyanite
    networks:
      - cyanite
    ports:
      - 8000:8000
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - "GF_LOG_MODE=console"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Editor"
      - "GF_AUTH_BASIC_ENABLED=false"
      - "GF_SNAPSHOTS_EXTERNAL_ENABLED=false"
      - "GF_SNAPSHOTS_EXTERNAL_SNAPSHOT_URL=http://localhost"
      - "GF_USERS_ALLOW_SIGN_UP=false"
      - "GF_SECURITY_LOGIN_REMEMBER_DAYS=1"
    netowrks:
      - cyanite
    depends_on:
      - graphite-api
networks:
  cyanite:
    driver: bridge
